MATRIX_URL="${MATRIX_URL:-}"
MATRIX_URL="${MATRIX_URL%/}"
MATRIX_ACCESS_TOKEN="${MATRIX_ACCESS_TOKEN:-}"
MATRIX_BOT_USER="${MATRIX_BOT_USER:-}"
MATRIX_ROOM_IDS="${MATRIX_ROOM_IDS:-}"
MATRIX_ROOM_ADMIN="${MATRIX_ROOM_ADMIN:-}"
MATRIX_ADMIN_USER="${MATRIX_ADMIN_USER:-}"
MAC_PC="${MAC_PC:-}"
SVC_WANTED="${SVC_WANTED:-}"
WIFI_DETAILED="${WIFI_DETAILED:-0}"
readonly MATRIX_URL MATRIX_ACCESS_TOKEN MATRIX_BOT_USER \
    MATRIX_ROOM_IDS MATRIX_ROOM_ADMIN MATRIX_ADMIN_USER \
    MAC_PC SVC_WANTED WIFI_DETAILED
