MATRIX_URL="${MATRIX_URL:-}"
MATRIX_URL="${MATRIX_URL%/}"
MATRIX_ACCESS_TOKEN="${MATRIX_ACCESS_TOKEN:-}"
MATRIX_ROOM_IDS="${MATRIX_ROOM_IDS:-}"
readonly MATRIX_URL MATRIX_ACCESS_TOKEN MATRIX_ROOM_IDS
