MATRIX_URL="${MATRIX_URL:-}"
MATRIX_URL="${MATRIX_URL%/}"
MATRIX_ACCESS_TOKEN="${MATRIX_ACCESS_TOKEN:-}"
MATRIX_BOT_USER="${MATRIX_BOT_USER:-}"
MATRIX_ROOM_IDS="${MATRIX_ROOM_IDS:-}"
MATRIX_ROOM_ADMIN="${MATRIX_ROOM_ADMIN:-}"
MATRIX_ADMIN_USER="${MATRIX_ADMIN_USER:-}"
SSH_HOST="${SSH_HOST:-}"
SSH_PORT="${SSH_PORT:-}"
SSH_USER="${SSH_USER:-}"
SSH_KEY="${SSH_KEY:-}"
MAC_PC="${MAC_PC:-}"
SVC_WANTED="${SVC_WANTED:-}"
WIFI_DETAILED="${WIFI_DETAILED:-0}"
WIFI_SHOW_KEY="${WIFI_SHOW_KEY:-0}"
readonly MATRIX_URL MATRIX_ACCESS_TOKEN MATRIX_BOT_USER \
    MATRIX_ROOM_IDS MATRIX_ROOM_ADMIN MATRIX_ADMIN_USER \
    SSH_HOST SSH_PORT SSH_USER SSH_KEY \
    MAC_PC SVC_WANTED WIFI_DETAILED WIFI_SHOW_KEY
