    SSH_HOST="${SSH_HOST:-}"
    SSH_PORT="${SSH_PORT:-}"
    SSH_USER="${SSH_USER:-}"
    SSH_KEY="${SSH_KEY:-}"
    readonly MATRIX_URL MATRIX_ACCESS_TOKEN MATRIX_ROOM_IDS \
        SSH_HOST SSH_PORT SSH_USER SSH_KEY
