-- luacheck: push ignore 121 122
package.loaded["nixio"] = require("tests.mocks.nixio")
-- luacheck: pop
local validator = require("matrixbot.utils.validator")

describe("validator module", function()
    describe("is_ipv4", function()
        it("validates correct IPv4", function()
            assert.is_true(validator.is_ipv4("192.168.1.1"))
            assert.is_true(validator.is_ipv4("0.0.0.0"))
            assert.is_true(validator.is_ipv4("255.255.255.255"))
            assert.is_true(validator.is_ipv4("10.0.0.2"))
        end)

        it("rejects invalid IPv4", function()
            assert.is_false(validator.is_ipv4("192.168.1.256"))
            assert.is_false(validator.is_ipv4("192.168.1"))
            assert.is_false(validator.is_ipv4("192.168.1.1.1"))
            assert.is_false(validator.is_ipv4("192.168.01.1"))
            assert.is_false(validator.is_ipv4("192.168.1.a"))
            assert.is_false(validator.is_ipv4("..."))
            assert.is_false(validator.is_ipv4(""))
            assert.is_false(validator.is_ipv4(nil))
        end)
    end)

    describe("is_ipv6", function()
        it("validates correct IPv6", function()
            assert.is_true(validator.is_ipv6("2001:0db8:85a3:0000:0000:8a2e:0370:7334"))
            assert.is_true(validator.is_ipv6("::1"))
            assert.is_true(validator.is_ipv6("2001:db8::1"))
            assert.is_true(validator.is_ipv6("::"))
            assert.is_true(validator.is_ipv6("fe80::1ff:fe23:4567:890a"))
        end)

        it("rejects invalid IPv6", function()
            assert.is_false(validator.is_ipv6("2001:db8::1::2"))
            assert.is_false(validator.is_ipv6("2001:db8:::1"))
            assert.is_false(validator.is_ipv6("2001:db8:85a3:0000:0000:8a2e:0370:7334:1234"))
            assert.is_false(validator.is_ipv6("12001:db8::1"))
            assert.is_false(validator.is_ipv6("2001:xyz::1"))
            assert.is_false(validator.is_ipv6("::1:"))
            assert.is_false(validator.is_ipv6(":1::"))
        end)
    end)

    describe("is_domain", function()
        it("validates correct domain", function()
            assert.is_true(validator.is_domain("example.com"))
            assert.is_true(validator.is_domain("matrix.org"))
            assert.is_true(validator.is_domain("sub.domain.co.uk"))
            assert.is_true(validator.is_domain("my-domain.net"))
            assert.is_true(validator.is_domain("localhost"))
        end)

        it("rejects invalid domain", function()
            assert.is_false(validator.is_domain("-example.com"))
            assert.is_false(validator.is_domain("example.com-"))
            assert.is_false(validator.is_domain(".example.com"))
            assert.is_false(validator.is_domain("example..com"))
            assert.is_false(validator.is_domain("ex--ample.com"))
            assert.is_false(validator.is_domain("example.com/"))
            assert.is_false(validator.is_domain(""))
            assert.is_false(validator.is_domain(nil))
        end)
    end)

    describe("is_domain_port", function()
        it("validates correct domain with or without port", function()
            assert.is_true(validator.is_domain_port("example.com"))
            assert.is_true(validator.is_domain_port("example.com:8448"))
            assert.is_true(validator.is_domain_port("192.168.1.1"))
            assert.is_true(validator.is_domain_port("192.168.1.1:8080"))
            assert.is_true(validator.is_domain_port("[2001:db8::1]:443"))
            assert.is_true(validator.is_domain_port("[::1]"))
            assert.is_true(validator.is_domain_port("::1"))
            assert.is_true(validator.is_domain_port("2001:db8::1:80"))
        end)

        it("rejects invalid domain_port", function()
            assert.is_false(validator.is_domain_port("example.com:70000"))
            assert.is_false(validator.is_domain_port("example.com:abc"))
            assert.is_false(validator.is_domain_port("[192.168.1.1]:80"))
            assert.is_false(validator.is_domain_port(""))
        end)
    end)

    describe("validate_url", function()
        it("validates correct urls", function()
            assert.is_true(validator.validate_url("http://localhost"))
            assert.is_true(validator.validate_url("https://matrix.org"))
            assert.is_true(validator.validate_url("https://matrix.example.com:8448"))
            assert.is_true(validator.validate_url("http://192.168.1.1:8080"))
        end)

        it("rejects invalid urls", function()
            assert.is_false(validator.validate_url("ftp://matrix.org"))
            assert.is_false(validator.validate_url("https://"))
            assert.is_false(validator.validate_url("matrix.org"))
            assert.is_false(validator.validate_url("https://matrix.org:abc"))
            assert.is_false(validator.validate_url(""))
        end)
    end)

    describe("validate_token", function()
        it("validates correct tokens", function()
            assert.is_true(validator.validate_token("syt_someBase64_abc123"))
            assert.is_true(validator.validate_token("mct_someBase64_abc123"))
        end)

        it("rejects tokens with invalid prefix", function()
            assert.is_false(validator.validate_token("mat_shortlived_token"))
            assert.is_false(validator.validate_token("some_token_123"))
            assert.is_false(validator.validate_token("xyz_token"))
        end)

        it("rejects invalid tokens", function()
            assert.is_false(validator.validate_token("syt_token!"))
            assert.is_false(validator.validate_token("syt_token;rm -rf /"))
            assert.is_false(validator.validate_token("syt_token "))
            assert.is_false(validator.validate_token("syt_token-bad"))
            assert.is_false(validator.validate_token("mct_token.bad"))
            assert.is_false(validator.validate_token(""))
            assert.is_false(validator.validate_token(nil))
        end)
    end)

    describe("validate_matrix_user", function()
        it("validates correct users", function()
            assert.is_true(validator.validate_matrix_user("@user:matrix.org", "user"))
            assert.is_true(validator.validate_matrix_user("@admin_123:localhost", "user"))
            assert.is_true(validator.validate_matrix_user("@my-user.name=/:192.168.1.1:8448", "user"))
            assert.is_true(validator.validate_matrix_user("", "user"))
        end)

        it("rejects invalid users", function()
            assert.is_false(validator.validate_matrix_user("user:matrix.org", "user"))
            assert.is_false(validator.validate_matrix_user("@:matrix.org", "user"))
            assert.is_false(validator.validate_matrix_user("@user:", "user"))
            assert.is_false(validator.validate_matrix_user("@user:matrix.org:abc", "user"))
            assert.is_false(validator.validate_matrix_user("@us er:matrix.org", "user"))
        end)
    end)

    describe("validate_matrix_room", function()
        it("validates correct rooms", function()
            assert.is_true(validator.validate_matrix_room("!room_id:matrix.org", "room"))
            assert.is_true(validator.validate_matrix_room("!0xRqYq5IIruJFFcCLhkzepUfk5m2InboNUkXe3ZTqPs", "room"))
            assert.is_true(validator.validate_matrix_room("", "room"))
        end)

        it("rejects invalid rooms", function()
            assert.is_false(validator.validate_matrix_room("@room_id:matrix.org", "room"))
            assert.is_false(validator.validate_matrix_room("!room:matrix.org!", "room"))
            assert.is_false(validator.validate_matrix_room("!", "room"))
            assert.is_false(validator.validate_matrix_room("!room:", "room"))
        end)
    end)

    describe("validate_mac", function()
        it("validates correct MACs", function()
            assert.is_true(validator.validate_mac("00:11:22:33:44:55", "mac"))
            assert.is_true(validator.validate_mac("aa:bb:cc:dd:ee:ff", "mac"))
            assert.is_true(validator.validate_mac("A1:B2:C3:D4:E5:F6", "mac"))
            assert.is_true(validator.validate_mac("", "mac"))
        end)

        it("rejects invalid MACs", function()
            assert.is_false(validator.validate_mac("00-11-22-33-44-55", "mac"))
            assert.is_false(validator.validate_mac("00:11:22:33:44", "mac"))
            assert.is_false(validator.validate_mac("00:11:22:33:44:55:66", "mac"))
            assert.is_false(validator.validate_mac("zz:11:22:33:44:55", "mac"))
        end)
    end)

    describe("validate_path_list", function()
        it("validates correct lists", function()
            assert.is_true(validator.validate_path_list({ "network", "firewall", "/etc/config/dropbear" }, "list"))
            assert.is_true(validator.validate_path_list({}, "list"))
            assert.is_true(validator.validate_path_list(nil, "list"))
        end)

        it("rejects invalid lists", function()
            assert.is_false(validator.validate_path_list({ "network", "rm -rf /" }, "list"))
            assert.is_false(validator.validate_path_list({ "service; reboot" }, "list"))
        end)
    end)
end)
